sudo: required
language: python
python:
    - 3.6
services:
    - docker
before_install:
    - docker build -t orders .
install:
    - pip install -r requirements.txt
script:
    - python manage.py test
