# Generated by Django 2.0.3 on 2018-10-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181029_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='kind',
        ),
    ]
