# Generated by Django 2.0.3 on 2018-10-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_pizza_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='kind',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
