# Generated by Django 2.0.3 on 2018-10-30 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_pizza_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('dinner', models.ManyToManyField(blank=True, related_name='diner', to='orders.DinnerPlatter')),
                ('pasta', models.ManyToManyField(blank=True, related_name='pasta', to='orders.Pasta')),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='subs',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ManyToManyField(blank=True, related_name='pizza', to='orders.Pizza'),
        ),
        migrations.AddField(
            model_name='order',
            name='salad',
            field=models.ManyToManyField(blank=True, related_name='salad', to='orders.Salad'),
        ),
        migrations.AddField(
            model_name='order',
            name='sub',
            field=models.ManyToManyField(blank=True, related_name='sub', to='orders.Sub'),
        ),
        migrations.AddField(
            model_name='order',
            name='topping',
            field=models.ManyToManyField(blank=True, related_name='topping', to='orders.Topping'),
        ),
    ]
