# Generated by Django 2.0.3 on 2018-11-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20181030_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='size',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
