# Generated by Django 2.0.3 on 2018-11-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20181111_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='topping',
            field=models.ManyToManyField(blank=True, related_name='topp', to='orders.Topping'),
        ),
    ]
