# Generated by Django 2.0.3 on 2018-11-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_pizza_topping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='topping',
        ),
    ]
