# Generated by Django 2.0.3 on 2018-11-12 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20181111_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.DinnerPlatter')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSalad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='dinner',
        ),
        migrations.AddField(
            model_name='order',
            name='dinner',
            field=models.ManyToManyField(blank=True, related_name='diner', through='orders.OrderDinner', to='orders.DinnerPlatter'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='salad',
        ),
        migrations.AddField(
            model_name='order',
            name='salad',
            field=models.ManyToManyField(blank=True, related_name='salad', through='orders.OrderSalad', to='orders.Salad'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='sub',
        ),
        migrations.AddField(
            model_name='order',
            name='sub',
            field=models.ManyToManyField(blank=True, related_name='sub', through='orders.OrderSub', to='orders.Sub'),
        ),
        migrations.AddField(
            model_name='ordersub',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AddField(
            model_name='ordersub',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Sub'),
        ),
        migrations.AddField(
            model_name='ordersalad',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AddField(
            model_name='ordersalad',
            name='salad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Salad'),
        ),
        migrations.AddField(
            model_name='orderdinner',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
