# Generated by Django 2.0.3 on 2018-11-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20181112_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dinner',
            field=models.ManyToManyField(blank=True, null=True, related_name='diner', through='orders.OrderDinner', to='orders.DinnerPlatter'),
        ),
    ]
