# Generated by Django 2.0.3 on 2018-11-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20181112_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dinner',
            field=models.ManyToManyField(blank=True, related_name='diner', through='orders.OrderDinner', to='orders.DinnerPlatter'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
