# Generated by Django 2.0.3 on 2018-11-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20181112_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizza',
            field=models.ManyToManyField(blank=True, null=True, related_name='pizza', through='orders.OrderPizza', to='orders.Pizza'),
        ),
        migrations.AlterField(
            model_name='orderpizza',
            name='topping',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Topping'),
        ),
    ]
