# Generated by Django 2.0.3 on 2018-11-13 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20181113_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpizza',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Pizza'),
        ),
        migrations.AlterField(
            model_name='orderpizza',
            name='topping',
            field=models.ManyToManyField(blank=True, null=True, related_name='topping', to='orders.Topping'),
        ),
    ]
