# Generated by Django 2.0.3 on 2018-11-13 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20181113_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizza',
            field=models.ManyToManyField(blank=True, related_name='pizza', through='orders.OrderPizza', to='orders.Pizza'),
        ),
        migrations.AlterField(
            model_name='orderpizza',
            name='pizza',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Pizza'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderpizza',
            name='topping',
            field=models.ManyToManyField(blank=True, related_name='topping', to='orders.Topping'),
        ),
    ]
