# Generated by Django 2.0.3 on 2018-11-13 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20181113_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpizza',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Pizza'),
        ),
    ]
